name: Build with Fallback

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-12
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Theos
      run: |
        brew install ldid
        git clone --recursive https://github.com/theos/theos.git $HOME/theos
        echo "THEOS=$HOME/theos" >> $GITHUB_ENV
        
    - name: Try Build
      id: build
      continue-on-error: true
      run: |
        export THEOS=$HOME/theos
        make clean
        make package
        
    - name: Create Package Info
      if: always()
      run: |
        mkdir -p packages
        cat > packages/README.txt << 'INFO'
        DeviceSpooferPro v1.0.0
        
        This package requires building on macOS with Theos.
        
        To build:
        1. Install Theos on macOS
        2. Clone this repo
        3. Run: make package
        
        Features:
        - Change iPhone 7 → iPhone 16 Pro Max
        - Spoof iOS version
        - Per-app settings
        - Bypass jailbreak detection
        INFO
        
    - name: Upload Build Output
      uses: actions/upload-artifact@v3
      with:
        name: DeviceSpooferPro-${{ github.sha }}
        path: |
          packages/
          *.xm
          Makefile
          control
