name: Build DeviceSpooferPro

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-12
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Install Dependencies
      run: |
        brew install ldid
    
    - name: Install Theos
      run: |
        git clone --recursive https://github.com/theos/theos.git $HOME/theos
        
    - name: Build Package
      env:
        THEOS: ${{ github.workspace }}/../theos
      run: |
        export THEOS=$HOME/theos
        export PATH=$THEOS/bin:$PATH
        make clean
        make package FINALPACKAGE=1 || true
        
    - name: Check Build Output
      run: |
        ls -la
        ls -la packages/ || echo "No packages directory"
        
    - name: Create Test Package
      if: failure()
      run: |
        mkdir -p packages
        echo "Test package" > packages/test.deb
        
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: DeviceSpooferPro-build-${{ github.run_number }}
        path: |
          packages/*.deb
          .theos/last_package
          
    - name: Create Release
      if: github.ref == 'refs/heads/main' && success()
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v1.0.${{ github.run_number }}
        name: Release v1.0.${{ github.run_number }}
        files: packages/*.deb
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
